name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: '14'

      - name: Install Dependencies
        run:  npm install mocha

      - name: Install Project Dependencies
        run: npm install

      - name: Run Mocha Tests
        run: npm test
      
      - name: BMS monitor
        run: node bms-monitor.js

